from typing import Literal

Mode = Literal["solo", "team"]
Character = Literal[
    "Baby Mario",
    "Baby Luigi",
    "Baby Peach",
    "Baby Daisy",
    "Toad",
    "Toadette",
    "Koopa Troopa",
    "Dry Bones",
    "Mario",
    "Luigi",
    "Peach",
    "Daisy",
    "Yoshi",
    "Birdo",
    "Diddy Kong",
    "Bowser Jr",
    "Wario",
    "Waluigi",
    "Donkey Kong",
    "Bowser",
    "King Boo",
    "Rosalina",
    "Funky Kong",
    "Dry Bowser",
    "Mii A",
    "Mii B",
]
Vehicle = Literal[
    "Standard Kart S",
    "Standard Bike S",
    "Baby Booster",
    "Bullet Bike",
    "Concerto",
    "Nanobike",
    "Standard Kart M",
    "Standard Bike M",
    "Nostalgia 1",
    "Mach Bike",
    "Wild Wing",
    "Bon Bon",
    "Standard Kart L",
    "Standard Bike L",
    "Offroader",
    "Bowser Bike",
    "Flame Flyer",
    "Wario Bike",
    "Cheep Charger",
    "Quacker",
    "Rally Romper",
    "Magikruiser",
    "Blue Falcon",
    "Bubble Bike",
    "Turbo Blooper",
    "Rapide",
    "Royal Racer",
    "Nitrocycle",
    "B Dasher MK 2",
    "Dolphin Dasher",
    "Piranha Prowler",
    "Twinkle Star",
    "Aero Glider",
    "Torpedo",
    "Dragonetti",
    "Phantom",
]
DriftMode = Literal["automatic", "manual"]
Course = Literal[
    "Luigi Circuit",
    "Moo Moo Meadows",
    "Mushroom Gorge",
    "Toad's Factory",
    "Mario Circuit",
    "Coconut Mall",
    "DK Summit",
    "Wario's Gold Mine",
    "Daisy Circuit",
    "Koopa Cape",
    "Maple Treeway",
    "Grumble Volcano",
    "Dry Dry Ruins",
    "Moonview Highway",
    "Bowser's Castle",
    "Rainbow Road",
    "GCN Peach Beach",
    "DS Yoshi Falls",
    "SNES Ghost Valley 2",
    "N64 Mario Raceway",
    "N64 Sherbet Land",
    "GBA Shy Guy Beach",
    "DS Delfino Square",
    "GCN Waluigi Stadium",
    "DS Desert Street",
    "GBA Bowser Castle 3",
    "N64 DK's Jungle Parkway",
    "GCN Mario Circuit",
    "SNES Mario Circuit 3",
    "DS Peach Gardens",
    "GCN DK Mountain",
    "N64 Bowser's Castle",
]

Cc = Literal[50, 100, 150, "mirror"]
Cpu = Literal["easy", "normal", "hard", "off"]
VehicleRule = Literal["all", "karts", "bikes"]
CourseRule = Literal["choose", "random", "in order"]
ItemRule = Literal["recommended", "frantic", "basic", "none"]
Races = Literal[2, 3, 4, 5, 8, 10, 12, 16, 32]
VehicleSize = Literal["small", "medium", "large"]
